### PR TITLE
[fix] crypto/converter: Use an alternative approach to copy array buffer

### PR DESCRIPTION
**Pull request by laumair**
On android (react-native) lead to `undefined is not a function (evaluating 'HALF_3.slice(0)'`. 
Covers that with an alternative approach to copy an ArrayBuffer. 
Thanks to @th0br0

### CODE REVIEW

**Comment by th0br0** [comment]
This might just be masking the bug because the TravisCI VM never executes `clone_uint32array`. Could you please post the output of the relevant tests when running in the Android interpreter?

**Comment by laumair** [comment]
That's a fairly good point. I'll do that.

**Comment by laumair** [comment]
all good
@th0br0 All tests pass. 

Weird thing is they also pass on master.

**Comment by laumair** [comment]
However, with doesn't throw on `slice` with these changes.

**Pull request closed without merging**
